\mainmatter

# (PART) Part I: Getting ready for submission {-}

# The hypo-deductive model in science {#Week2}

Content of Week 2

## The hypo-deductive model in science


 - big questions in your field
 - reviewing the literature
 - how to write a hypothesis
 - citing the literature


The slides for Week 2's lecture will appear here.

***

## What is a citation?

Citations are a means of recognising that your work is built on the work of others. They are part of the fundamental tenets of science that we don’t start from nothing each time we conduct a study.


 - Names of three or more authors are frequently reduced to ‘et al.’ (often written in italics: *et al.*) which is short for the Latin *et alia*, meaning ‘and others’.

***

## Dunleavy’s 7 criteria for academic research 

| Defining attributes of academic work | What the attribute means | The related role of citations and referencing |
| - | - | - |
| Formally stated | Premises and assumptions are explicit, and arguments are precisely expressed | To specify sources for assumptions and their contextual legitimacy, and to contextualise arguments within a defined field |
| Part of an advanced conversation | Academic work expresses a lot of content in a brief space, using specialist terminology or notations | To set up a specialist discourse in an economical and highly-focused manner, and to show how the relevant literature defines concepts, terms or notations |
| Cumulative | Arguments are built up layer by layer | To show that the author has read the relevant literature and has a good understanding of it |
| Tackling difficult issues | Academic work goes beyond common-sense understandings and (generally) seeks theory-based and non-obvious explanations of complex, hard-to-understand phenomena | To guide readers seeking to follow the author’s extended chain of reasoning. Readers should be able to understand and “replay” the intellectual journey involved |
| Collegial | Professionals carefully accord credit to other authors where it is due. STEM disciplines assign special emphasis to those who are first in discovering or correctly understanding phenomena (primacy) | To accurately assign credit to other researchers for key innovations and relevant prior findings or arguments, so that readers can also access this work for themselves |
| Evidence-based | Arguments are grounded in proofs, recorded facts, or other auditable tokens. The provenance of all claims should be checkable | To allow readers to quickly find and precisely check sources of evidence or other tokens for themselves. An extended version of this criterion, now dominant in more and more STEM and social sciences fields, is that all published work should include a replication archive with data and guidance to make it reproducible |
| Empirically consistent | Evidence and arguments are related to other views or findings, and divergences are explained. In STEM subjects there is a general premium on considering all scientific evidence on the exact same topic, carried through most strongly in “systematic review”. Elsewhere this criterion is often more loosely interpreted | To show that the author has comprehensively surveyed work that is relevant in scope, approach and recency, and to specifically point out consistencies and inconsistencies between other work and the author’s own findings |

Taken from Dunleavy, P. (2017) Citations are more than merely assigning credit – their inclusion (or not) conditions how colleagues regard and evaluate your work. *LSE Blog*. Available at https://blogs.lse.ac.uk/impactofsocialsciences/2017/04/06/citations-are-more-than-merely-assigning-credit/


***

## Your citations say a lot about you


 - What you cite explains what you have read 
 - Shows the strength on which you build your argument
 - What you find credible (if you support) or not credible (if you oppose)
 - **Most importantly**
    + **Citations MUST support your statement**
  
***  
    
## Old or New? High or Low IF? Friends or colleagues? 

Cite original ideas (primacy)
 - Include solid newer work (relevance)
 - Include meta-analyses (coverage)
 
 
Work should be well designed and implemented for you to cite it 
 - Forget IF
 - Forget friends and colleagues
 - Concentrate on the science


Specialists (reviewers and examiners) will know the literature

***

## Self-citations

In the Natural Sciences self-citations run at 33% (van Raan et al. 2007)
 - This is for all authors in the author line (not just you!)


You are likely to cite yourself because you have written relevant papers
 - But don’t self-cite to the exclusion of others
 - Include contrary citations


***

## How many citations?

 - 3-4 good citations will make most points solid
 - Avoid lists
 - Pull apart variables or taxa
 - If you state “recent” they must be recent (<5 years)!
 - Be aware of total word counts and maximum citations


## What is a mis-citation?

Citations that do not support the statement


 - Do not cite unless the study shows evidence to support the claim
 - Never have empty citations (cite someone who cites someone else)


In ecology ~25% of citations are incorrect (Todd et al. 2007)


 - 11% ambiguous
 - 7% do not support statement
 - 5% empty = ‘lazy author syndrome’


***

## Always cite while you write (never later)

You should always know the relevant literature to what you are writing

 - Otherwise, you need to take the time to read
 - You must have read (& understood) everything you cite
   + This is the foundation on which you build your work
 - Never write a statement and look for a citation later

***

## Use a citation manager

 - What does it cost?
    + If free - what are you giving up and to whom?
 - What do people in your group use?
    + Will you get support?
 - Does it support your journals?
 - Does it deal with retractions?
 - Can you read and make notes?
 - Can you share your papers?

***

## Citation style

 - Vancouver style
 
  - Harvard style
  
*** 

## Where to place the citation

***

## 







